/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as DeudasRouteImport } from './routes/deudas'
import { Route as DineroRouteImport } from './routes/dinero'
import { Route as NotasRouteImport } from './routes/notas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const DeudasRoute = DeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => rootRouteImport,
} as any)
const DineroRoute = DineroRouteImport.update({
  id: '/dinero',
  path: '/dinero',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/compras': typeof ComprasRoute
  '/deudas': typeof DeudasRoute
  '/dinero': typeof DineroRoute
  '/notas': typeof NotasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/compras': typeof ComprasRoute
  '/deudas': typeof DeudasRoute
  '/dinero': typeof DineroRoute
  '/notas': typeof NotasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/compras': typeof ComprasRoute
  '/deudas': typeof DeudasRoute
  '/dinero': typeof DineroRoute
  '/notas': typeof NotasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agenda' | '/compras' | '/deudas' | '/dinero' | '/notas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agenda' | '/compras' | '/deudas' | '/dinero' | '/notas'
  id:
    '__root__' | '/' | '/agenda' | '/compras' | '/deudas' | '/dinero' | '/notas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ComprasRoute: typeof ComprasRoute
  DeudasRoute: typeof DeudasRoute
  DineroRoute: typeof DineroRoute
  NotasRoute: typeof NotasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deudas': {
      id: '/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof DeudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinero': {
      id: '/dinero'
      path: '/dinero'
      fullPath: '/dinero'
      preLoaderRoute: typeof DineroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ComprasRoute: ComprasRoute,
  DeudasRoute: DeudasRoute,
  DineroRoute: DineroRoute,
  NotasRoute: NotasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
